const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],COLORS=DATA.colors,GROUPS=DATA.groups,FAMILIES=DATA.families
const fmt=v=>v==null||!Number.isFinite(+v)?'—':`${+v>=0?'+':''}${(+v).toFixed(1)}`,pct=v=>`${Math.round(v*100)}%`
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const groupOf=r=>GROUPS.find(g=>g.rank===r),color=r=>COLORS[(r-1)%COLORS.length]
const memberById=new Map(DATA.members.map(m=>[m.person_id,m]))
/* Names printed in capitals in the records display in title case; mixed-case names are untouched. */
const displayName=s=>{const t=String(s??'');return /[a-z]/.test(t)?t:t.toLowerCase().replace(/(^|[\s\-'’.])([a-z])/g,(m,p,c)=>p+c.toUpperCase()).replace(/\bMc([a-z])/g,(m,c)=>'Mc'+c.toUpperCase()).replace(/\b(Ii|Iii|Iv)\b/g,m=>m.toUpperCase())}
let selected=null,brushed=null
/* A second channel besides color: each group also has its own mark shape. */
function shape(rank,r){const k=(rank-1)%5,f=color(rank),st='stroke="#1d2228" stroke-width="0.9"';if(k===0)return `<circle r="${r}" fill="${f}" ${st}/>`;if(k===1)return `<rect x="${-r*.85}" y="${-r*.85}" width="${r*1.7}" height="${r*1.7}" fill="${f}" ${st}/>`;if(k===2)return `<path d="M0,${-r*1.15}L${r*1.15},0L0,${r*1.15}L${-r*1.15},0Z" fill="${f}" ${st}/>`;if(k===3)return `<path d="M0,${-r*1.1}L${r*1.05},${r*.8}L${-r*1.05},${r*.8}Z" fill="${f}" ${st}/>`;const a=r*.38,b=r*1.05;return `<path d="M${-a},${-b}H${a}V${-a}H${b}V${a}H${a}V${b}H${-a}V${a}H${-b}V${-a}H${-a}Z" fill="${f}" ${st}/>`}
const markSvg=(rank,size=14)=>`<svg class="mark" viewBox="-8 -8 16 16" width="${size}" height="${size}" aria-hidden="true">${shape(rank,6)}</svg>`
/* Rows read liberal-left: the family's liberal pole (LIBERAL_POLE in the builder) is always drawn on the left. */
const oriented=(f,v)=>v==null?null:(f.liberalPole==='positive'?-v:v)
const leftPole=f=>f.liberalPole==='positive'?f.positivePole:f.negativePole
const rightPole=f=>f.liberalPole==='positive'?f.negativePole:f.positivePole
/* Label color with the higher WCAG contrast against the fill. */
function textOn(hex){const l=luminance(hex);return (1.05/(l+.05))>=((l+.05)/.0658)?'#fff':'#1d2228'}
function luminance(hex){const c=hex.match(/\w\w/g).map(x=>{const v=parseInt(x,16)/255;return v<=.03928?v/12.92:((v+.055)/1.055)**2.4});return .2126*c[0]+.7152*c[1]+.0722*c[2]}

function hover(node,html){node.onpointerenter=e=>{const t=$('#tip');t.innerHTML=html;t.style.display='block';moveTip(e)};node.onpointermove=moveTip;node.onpointerleave=()=>$('#tip').style.display='none'}
function moveTip(e){const t=$('#tip'),pad=14;t.style.left=Math.min(innerWidth-t.offsetWidth-pad,e.clientX+14)+'px';t.style.top=Math.min(innerHeight-t.offsetHeight-pad,e.clientY+14)+'px'}

function renderHeadline(){const sorted=GROUPS.slice().sort((a,b)=>a.cycleWarMean-b.cycleWarMean),low=sorted[0],high=sorted.at(-1);$('#headlineFinding').innerHTML=`<b>Headline result:</b> ${esc(low.label)} average <b>${fmt(low.cycleWarMean)}</b> margin points of WAR per contested race, against <b>${fmt(high.cycleWarMean)}</b> for ${esc(high.label)}. Pre-2016 races are scored against modern partisan expectations, which lifts early-era groups by construction; the ordering survives era-normalised regrouping, the levels do not.`}

function renderGroups(){$('#groupGrid').innerHTML=GROUPS.map(g=>`<article class="group-card" style="border-top-color:${color(g.rank)}"><h3>${markSvg(g.rank,16)}${esc(g.label)}</h3><div class="count">${g.people} people · ${g.candidateCycles} candidate-cycles</div><p>${esc(g.description)}</p><div class="metric-grid"><div><b>${fmt(g.cycleWarMean)}</b><span>Mean cycle WAR (SE ${g.cycleWarSe==null?'—':g.cycleWarSe.toFixed(2)})</span></div><div><b>${fmt(g.careerWarMedian)}</b><span>Median career WAR</span></div><div><b>${g.cyclesScored}</b><span>Scored cycles</span></div><div><b>${pct(g.unscoredShare)}</b><span>Cycles with no contested race</span></div></div></article>`).join('')}

function legend(node){$(node).innerHTML=GROUPS.map(g=>`<li>${markSvg(g.rank)}${esc(g.label)}</li>`).join('')}

function renderProfiles(){$('#profileChart').innerHTML=FAMILIES.map(f=>{const placed=[];const marks=GROUPS.map(g=>{const cell=g.profile.find(p=>p.family===f.key),o=cell?oriented(f,cell.value):null;if(o==null)return '';const near=placed.filter(q=>Math.abs(q-o)<.035).length;placed.push(o);const top=4+(near?(near%2?-7:7)*Math.ceil(near/2):0);return `<svg viewBox="-9 -9 18 18" style="left:${(50+45*o).toFixed(2)}%;top:${top}px" role="img" aria-label="${esc(g.label)}: ${cell.value.toFixed(2)} on the ${esc(f.negativePole)} (−1) to ${esc(f.positivePole)} (+1) scale, ${cell.people} people"><title>${esc(g.label)}: ${cell.value.toFixed(2)} (${cell.people} people)</title>${shape(g.rank,6.5)}</svg>`}).join('');const observed=GROUPS.reduce((s,g)=>s+(g.profile.find(p=>p.family===f.key)?.people||0),0);return `<div class="profile-row"><span>${esc(f.label)}</span><div class="profile-scale"><div class="profile-ends"><span>← ${esc(leftPole(f))}</span><span>${esc(rightPole(f))} →</span></div><div class="profile-track">${marks}</div></div><output>${observed} people</output></div>`}).join('')}

/* People on two issue families, with group outlines and a drag-to-select brush. */
function hull(points){const p=points.slice().sort((a,b)=>a[0]-b[0]||a[1]-b[1]);if(p.length<3)return p;const cross=(o,a,b)=>(a[0]-o[0])*(b[1]-o[1])-(a[1]-o[1])*(b[0]-o[0]),lo=[],up=[];for(const q of p){while(lo.length>=2&&cross(lo.at(-2),lo.at(-1),q)<=0)lo.pop();lo.push(q)}for(const q of p.slice().reverse()){while(up.length>=2&&cross(up.at(-2),up.at(-1),q)<=0)up.pop();up.push(q)}return lo.slice(0,-1).concat(up.slice(0,-1))}
function nudge(id,k){let h=2166136261;for(const ch of id+k){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return ((h>>>0)%1000)/1000-.5}
function renderScatter(){
  const fx=FAMILIES.find(f=>f.key==='market_government_direction')||FAMILIES[0],fy=FAMILIES.find(f=>f.key==='social_liberty_equality')||FAMILIES[1],ix=FAMILIES.indexOf(fx),iy=FAMILIES.indexOf(fy)
  const W=Math.round(Math.min(760,Math.max(300,($('#scatter').clientWidth||720)))),H=Math.round(W*.75),L=46,T=34,PW=W-L-20,PH=H-T-70,X=o=>L+PW*(o+1)/2,Y=o=>T+PH*(o+1)/2
  const pts=DATA.members.map(m=>{const pos=DATA.positions[m.person_id];if(!pos||pos[ix]==null||pos[iy]==null)return null;const ox=oriented(fx,pos[ix]),oy=oriented(fy,pos[iy]);return {m,x:X(Math.max(-1,Math.min(1,ox+.04*nudge(m.person_id,'x')))),y:Y(Math.max(-1,Math.min(1,oy+.04*nudge(m.person_id,'y'))))}}).filter(Boolean)
  const hulls=GROUPS.map(g=>{const h=hull(pts.filter(p=>p.m.cluster_rank===g.rank).map(p=>[p.x,p.y]));return h.length>2?`<path class="hull" data-rank="${g.rank}" d="M${h.map(q=>q.map(v=>v.toFixed(1)).join(',')).join('L')}Z" fill="${color(g.rank)}" fill-opacity=".12" stroke="${g.rank===2?'#1d2228':color(g.rank)}" stroke-width="2" visibility="hidden"/>`:''}).join('')
  const grid=[-1,-.5,0,.5,1].map(t=>`<line x1="${X(t)}" x2="${X(t)}" y1="${T}" y2="${T+PH}" stroke="${t?'var(--rule-soft)':'var(--muted)'}"/><line x1="${L}" x2="${L+PW}" y1="${Y(t)}" y2="${Y(t)}" stroke="${t?'var(--rule-soft)':'var(--muted)'}"/>`).join('')
  $('#scatter').innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="group" aria-label="${pts.length} grouped people placed by ${esc(fx.label)} and ${esc(fy.label)}">${grid}${hulls}<g class="pts">${pts.slice().sort((a,b)=>a.x-b.x||a.y-b.y).map(p=>`<g data-id="${esc(p.m.person_id)}" role="button" tabindex="-1" aria-label="${esc(displayName(p.m.name))}, ${esc(p.m.cluster_label)}" transform="translate(${p.x.toFixed(1)},${p.y.toFixed(1)})">${shape(p.m.cluster_rank,W<500?3.6:4.6)}</g>`).join('')}</g><rect class="brush" id="brushRect" width="0" height="0" visibility="hidden"/><text x="${L+PW/2-8}" y="${T+PH+32}" text-anchor="end" font-size="12" fill="var(--ink)">← ${esc(leftPole(fx))}</text><text x="${L+PW/2+8}" y="${T+PH+32}" text-anchor="start" font-size="12" fill="var(--ink)">${esc(rightPole(fx))} →</text><text x="${L+PW/2}" y="${T+PH+50}" text-anchor="middle" font-size="12" font-weight="700" fill="var(--ink)">${esc(fx.label)}</text><text x="${L+6}" y="${T-8}" font-size="12" fill="var(--ink)">↑ ${esc(leftPole(fy))}</text><text x="${L+6}" y="${T+PH+16}" font-size="12" fill="var(--ink)">↓ ${esc(rightPole(fy))}</text><text transform="translate(16,${T+PH/2}) rotate(-90)" text-anchor="middle" font-size="12" font-weight="700" fill="var(--ink)">${esc(fy.label)}</text></svg><p class="note">${pts.length} of ${DATA.members.length} grouped people have evidence on both families; marks are nudged slightly so identical positions stay visible. Outlines are statistical groupings, not formal caucuses. Keyboard: Tab to the marks, arrow keys to move, Enter to open a person; the group filter below the members table offers the same selection.</p>`
  const marks=$$('#scatter .pts g')
  marks.forEach((g,i)=>{const m=memberById.get(g.dataset.id);g.tabIndex=i===0?0:-1;hover(g,`<b>${esc(displayName(m.name))}</b><br>${esc(m.cluster_label)}<br>${m.first_cycle}–${m.last_cycle}`);g.style.cursor='pointer';g.onclick=()=>{select(m.person_id);document.getElementById('members').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})};g.onkeydown=e=>{const moves={ArrowRight:1,ArrowDown:1,ArrowLeft:-1,ArrowUp:-1};if(e.key in moves){e.preventDefault();const n=marks[(i+moves[e.key]+marks.length)%marks.length];marks.forEach(x=>x.tabIndex=-1);n.tabIndex=0;n.focus()}else if(e.key==='Enter'||e.key===' '){e.preventDefault();select(m.person_id)}}})
  $('#scatterGroups').innerHTML=GROUPS.map(g=>`<li><button type="button" data-focus="${g.rank}" aria-pressed="false">${markSvg(g.rank)}${esc(g.label)}</button></li>`).join('')
  $$('[data-focus]').forEach(b=>b.onclick=()=>{const on=b.getAttribute('aria-pressed')!=='true';$$('[data-focus]').forEach(x=>x.setAttribute('aria-pressed',String(on&&x===b)));const rank=on?+b.dataset.focus:null;$$('#scatter .hull').forEach(h=>h.setAttribute('visibility',rank&&+h.dataset.rank===rank?'visible':'hidden'));$$('#scatter .pts g').forEach(g=>{const m=memberById.get(g.dataset.id);g.style.opacity=rank&&m.cluster_rank!==rank?'.18':(brushed&&!brushed.has(g.dataset.id)?'.2':'1')})})
  const svg=$('#scatter svg'),rect=$('#brushRect');let start=null
  const local=e=>{const b=svg.getBoundingClientRect();return [(e.clientX-b.left)*W/b.width,(e.clientY-b.top)*H/b.height]}
  svg.addEventListener('pointerdown',e=>{if(e.target.closest('.pts g'))return;start=local(e);svg.setPointerCapture(e.pointerId);rect.setAttribute('visibility','visible')})
  svg.addEventListener('pointermove',e=>{if(!start)return;const [x,y]=local(e);rect.setAttribute('x',Math.min(x,start[0]));rect.setAttribute('y',Math.min(y,start[1]));rect.setAttribute('width',Math.abs(x-start[0]));rect.setAttribute('height',Math.abs(y-start[1]))})
  svg.addEventListener('pointerup',e=>{if(!start)return;const [x,y]=local(e),x0=Math.min(x,start[0]),x1=Math.max(x,start[0]),y0=Math.min(y,start[1]),y1=Math.max(y,start[1]);start=null;rect.setAttribute('visibility','hidden');if(x1-x0<4&&y1-y0<4)return;brushed=new Set(pts.filter(p=>p.x>=x0&&p.x<=x1&&p.y>=y0&&p.y<=y1).map(p=>p.m.person_id));applyBrush()})
}
function applyBrush(){const bar=$('#selectionBar');$$('#scatter .pts g').forEach(g=>g.style.opacity=brushed&&!brushed.has(g.dataset.id)?'.2':'1');if(!brushed){bar.hidden=true;renderMembers();return}bar.hidden=false;bar.innerHTML=`<span><b>${brushed.size}</b> people selected; the members table below lists only them.</span><button type="button" id="clearBrush">Clear selection</button>`;$('#clearBrush').onclick=()=>{brushed=null;applyBrush()};renderMembers()}

/* Overperformance: one lane per group, dots spread so none overlap, mean labelled. */
function renderDistribution(){
  const mode=$('#measure').value,series=mode==='cycle'?DATA.warCycles.map(r=>({rank:r.cluster_rank,value:+r.candidate_cycle_war,label:`${r.cycle} ${String(r.chamber).toUpperCase()}-${r.district}`,name:memberById.get(r.person_id)?.name||''})):DATA.members.filter(m=>m.career_war!=null).map(m=>({rank:m.cluster_rank,value:+m.career_war,label:`${m.cycles_scored} scored cycles`,name:m.name}))
  const W=Math.max(320,($('#distribution').clientWidth||1000)-36),narrow=W<640,limit=Math.max(20,Math.ceil(Math.max(...series.map(s=>Math.abs(s.value)),1)/10)*10),L=narrow?10:Math.min(270,W*.3),R=narrow?3.6:4.6,X=v=>L+(W-L-(narrow?10:30))*(v+limit)/(2*limit)
  let y=34
  const lanes=GROUPS.map(g=>{const rows=series.filter(s=>s.rank===g.rank).sort((a,b)=>Math.abs(a.value)-Math.abs(b.value)),placed=[];for(const s of rows){const cx=X(s.value);let k=0,dy=0;for(;;k++){dy=(k%2?1:-1)*Math.ceil(k/2)*(2*R+.6);if(!placed.some(p=>Math.abs(p.cx-cx)<2*R+.6&&Math.abs(p.dy-dy)<2*R+.6))break}placed.push({s,cx,dy})}const spread=Math.max(R,...placed.map(p=>Math.abs(p.dy)))+R+8+(narrow?8:0),mid=y+spread;y=mid+spread+6;const mean=rows.length?rows.reduce((a,b)=>a+b.value,0)/rows.length:null;return {g,placed,mid,spread,mean}})
  const H=y+34,step=narrow?(limit<=40?20:40):(limit<=40?10:20),ticks=[];for(let t=-limit;t<=limit;t+=step)ticks.push(t)
  const box=$('#distribution')
  box.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="group" aria-label="${mode==='cycle'?'Cycle':'Career'} WAR by group">${ticks.map(t=>`<line x1="${X(t)}" x2="${X(t)}" y1="22" y2="${H-26}" stroke="${t?'var(--rule-soft)':'var(--ink)'}"/><text x="${X(t)}" y="${H-8}" text-anchor="middle" font-size="12" fill="var(--muted)">${t>0?'+':''}${t}</text>`).join('')}<text x="${X(-limit)}" y="14" font-size="12" font-weight="700" fill="var(--ink)">← ${narrow?'Behind':'Ran behind expectation'}</text><text x="${X(limit)}" y="14" text-anchor="end" font-size="12" font-weight="700" fill="var(--ink)">${narrow?'Ahead':'Ran ahead of expectation'} →</text>${lanes.map(l=>`<g>${narrow?`<text x="0" y="${(l.mid-l.spread+12).toFixed(1)}" font-size="12" font-weight="700" fill="var(--ink)">${esc(l.g.label)}</text>`:`<text x="${L-14}" y="${l.mid+4}" text-anchor="end" font-size="12.5" font-weight="700" fill="var(--ink)">${esc(l.g.label)}</text>`}${l.placed.map(p=>`<circle data-rank="${l.g.rank}" cx="${p.cx.toFixed(1)}" cy="${(l.mid+p.dy).toFixed(1)}" r="${R}" fill="${color(l.g.rank)}" stroke="#1d2228" stroke-width=".7" opacity=".85"><title>${esc(p.s.name)}, ${esc(p.s.label)}: ${fmt(p.s.value)}</title></circle>`).join('')}${l.mean==null?'':`<line x1="${X(l.mean)}" x2="${X(l.mean)}" y1="${(l.mid-l.spread+6).toFixed(1)}" y2="${(l.mid+l.spread-6).toFixed(1)}" stroke="var(--ink)" stroke-width="3"/><text x="${X(l.mean)+6}" y="${(l.mid-l.spread+(narrow?26:14)).toFixed(1)}" font-size="11" font-weight="700" fill="var(--ink)" stroke="#fff" stroke-width="3" paint-order="stroke">mean ${fmt(l.mean)}</text>`}</g>`).join('')}<text x="${L+(W-L-30)/2}" y="${H+4}" text-anchor="middle" font-size="12" fill="var(--muted)">${mode==='cycle'?'Candidate-oriented cycle WAR, margin points':'Career cumulative WAR, margin points'}</text></svg>`
}

function renderComposition(){const cycles=[...new Set(DATA.composition.map(x=>x.cycle))].sort((a,b)=>a-b);$('#compositionChart').innerHTML=cycles.map(c=>{const rows=DATA.composition.filter(x=>x.cycle===c),total=rows.reduce((s,x)=>s+x.n,0);return `<div class="stack-row"><strong>${c}</strong><div class="stack">${GROUPS.map(g=>{const n=rows.find(x=>x.cluster_rank===g.rank)?.n||0,share=total?n/total:0;return `<span style="width:${100*share}%;background:${color(g.rank)};color:${textOn(color(g.rank))}" title="${esc(g.label)}: ${n} of ${total}">${share>=.08?n:''}</span>`}).join('')}</div><small>n=${total}</small></div>`}).join('')}

function renderFunnel(){const c=DATA.coverage,rows=[['Democratic candidates, 1994–2022',c.people],['With any issue evidence',c.peopleWithEvidence],['Grouped (≥3 of 8 families)',c.peopleClustered]];$('#funnel').innerHTML=rows.map(([label,n])=>`<div class="funnel-row"><span>${esc(label)}</span><div class="funnel-bar" style="width:${100*n/c.people}%"></div><output>${n}</output></div>`).join('')+c.unclustered.map(u=>`<div class="funnel-row"><span>Not grouped — ${u.reason==='no_ontology_evidence'?'no issue evidence at all':'evidence on fewer than three families'}</span><div class="funnel-bar" style="width:${100*u.people/c.people}%;background:var(--rule)"></div><output>${u.people}</output></div>`).join('');$('#coverageGrid').innerHTML=[[c.candidateCycles,'Democratic candidate-cycles'],[c.cyclesScored,'Scored by WAR (contested D–R race)'],[c.cyclesUnscored,'No contested general election; not zero'],[c.peopleWithUnresolvedIdentity,'People with an unresolved identity']].map(([n,l])=>`<div><b>${Number(n).toLocaleString()}</b><span>${esc(l)}</span></div>`).join('')+c.channels.slice(0,4).map(ch=>`<div><b>${Number(ch.evidence_rows).toLocaleString()}</b><span>${esc(String(ch.channel).replaceAll('_',' '))} records · ${ch.people} people</span></div>`).join('')}

function renderSensitivity(){$('#sensitivity').innerHTML=DATA.sensitivity.map(s=>`<div class="sens-row"><span>${esc(s.test)}<p>${esc(s.reading)}</p></span><div class="sens-track" role="img" aria-label="${esc(s.test)} agreement ${s.statistic.toFixed(2)} of 1"><i class="sens-fill" style="width:${Math.max(0,Math.min(1,s.statistic))*100}%"></i></div><output>${s.statistic.toFixed(2)}</output></div>`).join('')}

function renderMembers(){const q=$('#search').value.toLowerCase(),filter=$('#groupFilter').value,rows=DATA.members.filter(m=>(!brushed||brushed.has(m.person_id))&&(filter==='all'||m.cluster_rank===+filter)&&(!q||`${m.name} ${m.chambers}`.toLowerCase().includes(q))).sort((a,b)=>(b.career_war??-1e9)-(a.career_war??-1e9));$('#memberRows').innerHTML=rows.map(m=>`<tr data-id="${esc(m.person_id)}" tabindex="0" class="${m.person_id===selected?'is-on':''}"><td>${esc(displayName(m.name))}</td><td>${m.first_cycle}–${m.last_cycle}</td><td>${markSvg(m.cluster_rank,11)} ${esc(m.cluster_label)}</td><td class="num">${m.features_observed}</td><td class="num">${fmt(m.career_war)}</td><td class="num">${m.cycles_scored}/${m.cycles_total}</td></tr>`).join('');$$('#memberRows tr').forEach(tr=>{tr.onclick=()=>select(tr.dataset.id);tr.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();tr.click()}}})}

function select(id){const m=memberById.get(id);if(!m)return;const fromRow=document.activeElement?.closest?.('#memberRows');selected=id;const pos=DATA.positions[id]||[];$('#detail').innerHTML=`<h3>${esc(displayName(m.name))}</h3><p>${esc(m.chambers)} · ${m.first_cycle}–${m.last_cycle} · ${markSvg(m.cluster_rank,11)} ${esc(m.cluster_label)}</p><div class="score">${fmt(m.career_war)}<span>Career cumulative WAR · ${m.cycles_scored} of ${m.cycles_total} cycles scored</span></div>${FAMILIES.map((f,i)=>{const o=oriented(f,pos[i]);return o==null?`<div class="detail-row"><span>${esc(f.label)}</span><span class="note" style="margin:0">No evidence</span><span></span></div>`:`<div class="detail-row"><span>${esc(f.label)}</span><i title="${esc(leftPole(f))} ← → ${esc(rightPole(f))}"><b style="left:${(50+50*o).toFixed(1)}%"></b></i><span>${pos[i].toFixed(2)}</span></div>`}).join('')}<p class="note" style="margin:8px 0 0">Bars run from the liberal pole (left) to the other pole (right). Era-normalised grouping places this person in group ${m.eraGroup}.</p>`;renderMembers();if(fromRow)document.querySelector(`#memberRows tr[data-id="${CSS.escape(id)}"]`)?.focus()}

function renderMethods(){const d=DATA.diagnostics,c=DATA.coverage,r=DATA.run;$('#methodCluster').textContent=`One career profile per person, from all ontology-v3 evidence. Features are the ${d.features} issue families; k-means with k chosen in 2–5 by bootstrap stability selected ${d.clusters} groups (silhouette ${d.silhouette.toFixed(3)}, mean bootstrap ARI ${d.bootstrapAri.toFixed(3)}, tenth percentile ${d.bootstrapAriP10.toFixed(3)}). ${pct(DATA.repeatedPeopleShare)} of grouped people ran in more than one cycle, which the person-level unit absorbs. Group labels were proposed from the profiles and approved by the author.`;$('#methodEvidence').textContent=`${c.channels.reduce((s,x)=>s+x.evidence_rows,0).toLocaleString()} evidence records across ${c.channels.length} channels cover ${c.peopleWithEvidence} of ${c.people} Democratic candidates; ${c.peopleClustered} meet the three-family minimum. Roll calls and sponsorships carry the most weight, questionnaires and endorsements less.`;$('#methodRun').textContent=`Caucus run ${r.caucusRunId}, generated ${r.generatedAt.slice(0,10)}, joined to historical WAR run ${r.historicalWarRunId}. Labels from ${r.labelsSource}.`}

$('#groupFilter').innerHTML='<option value="all">All groups</option>'+GROUPS.map(g=>`<option value="${g.rank}">${esc(g.label)}</option>`).join('')
let resizeTimer=null,lastWidth=innerWidth
addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(innerWidth===lastWidth)return;lastWidth=innerWidth;renderScatter();if(brushed)applyBrush();renderDistribution()},200)})
$('#measure').onchange=renderDistribution;$('#search').oninput=renderMembers;$('#groupFilter').onchange=renderMembers
renderHeadline();renderGroups();legend('#profileLegend');legend('#compositionLegend');renderProfiles();renderScatter();renderDistribution();renderComposition();renderFunnel();renderSensitivity();renderMembers();renderMethods()
