"""Publish the initial machine-readable catalog and sync it into the warehouse."""
from __future__ import annotations

import csv
from contextlib import closing

from warehouse import ROOT, connect, initialize

ASSETS = [
    ("southern_war_v3_release","csv_export","mart","data/processed/war/post2016_southern_war_v3/race_war.csv","scripts/retrain_post2016_southern_war_v3.py","state/cycle/chamber/district","active",None,"Published same-cycle residuals; research-only v4 is not substituted"),
    ("southern_historical_war_release","csv_export","mart","data/processed/war/southern_historical_war_v1/race_war.csv","scripts/build_southern_historical_war_v1.py","state/cycle/chamber/district","active",None,"2016-2024 strict race residuals; 2016 explicitly backcast; content-addressed manifest"),
    ("southern_map_geometry_manifest","csv_export","source","data/processed/source_audits/southern_legislative_geography_manifest.csv","scripts/acquire_southern_legislative_geography.py","state/cycle/chamber","active",None,"116 election-year Census display layers; immutable hashes and terms; not an allocation crosswalk"),
    ("southern_war_map_payload","publication","publication","docs/data/southern_war_map_payload.json","scripts/build_southern_war_map.py","state/cycle/chamber/district","active",None,"All 116 scheduled maps through 2024; scored races and unscored outlines remain distinct"),
    ("southern_war_map_join_audit","csv_export","qa","docs/data/southern_war_map_join_audit.csv","scripts/build_southern_war_map.py","state/cycle/chamber","active",None,"Geometry keys validity source hashes retained unsimplified outlines and vote conservation"),
    ("source_repair_audit","database_table","qa","qa_warehouse_source_repair","scripts/repair_warehouse_source_defects.py","issue_id","active",None,"Source-backed repair evidence, backup, build run, and unresolved/stale review scopes"),
    ("vote_quality_review","database_view","qa","qa_vote_observation_quality","scripts/repair_warehouse_source_defects.py","source/year/county/precinct/office/district/candidate/issue","active",None,"Natural-key collisions and fractional source values; not instructions to discard observations"),
    ("legiscan_reconciliation","database_view","qa","qa_legiscan_roll_call_reconciliation","scripts/load_legislative_warehouse.py","roll_call_id","active",None,"Reported totals and categories versus recorded member votes"),
    ("legiscan_complete_rollcalls","database_view","canonical","canonical_legiscan_roll_call","scripts/load_legislative_warehouse.py","roll_call_id","active",None,"Only category- and total-reconciled roll calls; source conflicts retained"),
    ("legiscan_complete_votes","database_view","canonical","canonical_legiscan_member_vote","scripts/load_legislative_warehouse.py","roll_call_id/people_id","active",None,"Recorded votes belonging to reconciled complete roll calls"),
    ("raw_sos_elections","raw_file","raw","data/raw/alabama_elections_and_geography/","scripts/sos_precinct.py","provider file + county/sheet","active",None,"Immutable official election archives"),
    ("source_vote_observations","database_table","source","vote_observations","scripts/build_election_database.py","source/year/county/precinct/office/district/candidate","active",None,"Normalized source observations; conflicting providers coexist"),
    ("canonical_votes","database_view","canonical","canonical_vote_observations","scripts/build_election_database.py","source observation natural key","active",None,"Authority-ranked election observations"),
    ("canonical_candidates","database_table","canonical","canonical_candidates","scripts/build_candidate_identity.py","canonical_candidate_id","active",None,"Canonical candidate-election identities"),
    ("people","database_view","canonical","dim_person","scripts/build_candidate_identity.py","person_id","active",None,"Canonical person dimension"),
    ("candidate_elections","database_view","canonical","fact_candidate_election","scripts/build_candidate_identity.py","canonical_candidate_id","active",None,"Canonical candidate-election facts"),
    ("candidate_aliases","database_view","canonical","bridge_person_alias","scripts/build_candidate_identity.py","person/source/year/candidate_key","active",None,"Accepted source alias evidence"),
    ("cmo_feature_mart","csv_export","mart","data/processed/elections/canonical_cmo_features.csv","scripts/build_canonical_cmo_features.py","cycle/chamber/district","compatibility",None,"Compatibility export pending mart table migration"),
    ("cmo_candidate_export","csv_export","mart","data/processed/elections/canonical_cmo_candidates.csv","scripts/build_canonical_cmo_features.py","canonical_candidate_id","compatibility","canonical_candidates","Compatibility export of canonical candidates"),
    ("historical_cmo_extension","csv_export","mart","data/processed/elections/historical_cmo_extension.csv","scripts/build_canonical_cmo_features.py","canonical_candidate_id","compatibility",None,"Provisional pre-2010 analytical extension"),
    ("raw_legiscan","raw_file","raw","data/raw/legiscan/alabama/","scripts/import_legiscan_alabama_rollcalls.py","LegiScan source IDs","active",None,"Immutable LegiScan session packages"),
    ("legiscan_bills_table","database_table","source","source_legiscan_bill","scripts/load_legislative_warehouse.py","bill_id","active",None,"Normalized LegiScan bills"),
    ("legiscan_rollcalls_table","database_table","source","source_legiscan_roll_call","scripts/load_legislative_warehouse.py","roll_call_id","active",None,"Recorded roll calls"),
    ("legiscan_votes_table","database_table","source","source_legiscan_member_vote","scripts/load_legislative_warehouse.py","roll_call_id/people_id","active",None,"Individual recorded votes"),
    ("legiscan_sponsors_table","database_table","source","source_legiscan_bill_sponsor","scripts/load_legislative_warehouse.py","bill_id/people_id/sponsor_order","active",None,"Bill sponsorship observations"),
    ("canonical_legislator_identity","database_view","canonical","canonical_legislator_identity","scripts/load_legislative_warehouse.py","people_id/person_id","active",None,"Human-approved candidate/legislator links"),
    ("legiscan_bills_csv","csv_export","source","data/processed/legislative/legiscan_alabama_bills.csv","scripts/import_legiscan_alabama_rollcalls.py","bill_id","compatibility","legiscan_bills_table","Compatibility export validated against warehouse"),
    ("legiscan_votes_csv","csv_export","source","data/processed/legislative/legiscan_alabama_individual_votes.csv","scripts/import_legiscan_alabama_rollcalls.py","roll_call/person","compatibility","legiscan_votes_table","Compatibility export validated against warehouse"),
    ("raw_finance","raw_file","raw","data/raw/finance/","scripts/build_multisource_finance_features.py","provider record ID","active",None,"Immutable state and FollowTheMoney files"),
    ("candidate_finance_mart","csv_export","mart","data/processed/war/ftm_race_finance_features.csv","scripts/build_multisource_finance_features.py","cycle/chamber/district","compatibility",None,"Planned finance mart table"),
    ("dime_recipients","database_table","source","source_dime_recipient","scripts/build_dime_finance_features.py","dime_recipient_cycle_id","active",None,"Normalized DIME Alabama legislative recipient-cycle records"),
    ("candidate_resource_mart","database_table","mart","mart_candidate_resources","scripts/build_dime_finance_features.py","canonical_candidate_id","active",None,"Authority-selected candidate resource observations with missing values preserved"),
    ("race_resource_mart","database_table","mart","mart_race_resource_features","scripts/build_dime_finance_features.py","year/chamber/district","active",None,"Complete-case race resource features"),
    ("dime_finance_build_manifest","publication","source","data/processed/war/dime_finance_build_manifest.json","scripts/build_dime_finance_features.py","build_run_id","active",None,"Source provenance code version configuration and hashes for DIME compatibility exports"),
    ("raw_census","raw_file","raw","data/raw/census/","scripts/build_geographic_crosswalks.py","Census GEOID","active",None,"Immutable Census archives and manifests"),
    ("precinct_district_weights","csv_export","canonical","data/processed/elections/canonical_precinct_district_weights.csv","scripts/build_canonical_geographic_weights.py","cycle/chamber/node/district","compatibility",None,"Planned canonical geography table"),
    ("forecast_features","csv_export","mart","data/processed/war/2026_prospective_features_and_forecast.csv","scripts/fit_2026_prospective_model.py","chamber/district","compatibility",None,"Versioned forecast mart migration pending"),
    ("published_cmo_v4_data","csv_export","publication","docs/data/cmo_v4_candidates.csv","scripts/build_war_story_page.py","candidate-cycle","active",None,"Current publication-only CMO export; never an upstream input"),
    ("raw_southern_sos_elections","raw_file","raw","data/raw/southern_sos_elections/","scripts/acquire_southern_sos_precinct_results.py","provider artifact path + SHA-256","active",None,"Immutable official Southern election downloads; availability varies by state and cycle"),
    ("southern_election_source_files","database_table","source","source_southern_election_file","scripts/load_southern_election_warehouse.py","source_file_id","active",None,"Contract-complete Southern source registry with explicit unknown terms and geography vintages"),
    ("southern_candidate_results","database_table","source","source_southern_candidate_election","scripts/load_southern_election_warehouse.py","candidate_election_id","active",None,"Official candidate-party-contest totals at provider-reported contest geography"),
    ("southern_candidate_facts","database_view","canonical","fact_southern_candidate_election","scripts/load_southern_election_warehouse.py","candidate_election_id","active",None,"Validated official cross-state candidate-election interface"),
    ("southern_election_coverage","database_table","qa","qa_southern_election_coverage","scripts/load_southern_election_warehouse.py","state_code/cycle","active",None,"Acquisition and normalization status for the full Southern state universe"),
    ("southern_candidate_results_export","csv_export","source","data/processed/elections/southern_state_candidate_results.csv.gz","scripts/load_southern_election_warehouse.py","candidate_election_id","compatibility","southern_candidate_results","Versioned compatibility export generated from the same validated run"),
    ("raw_southern_legislative_history","raw_file","raw","data/raw/historical_statewide_elections/","scripts/load_southern_legislative_history_warehouse.py","artifact path + SHA-256","active",None,"Immutable Klarner MEDSL and modern Southern legislative source files"),
    ("southern_legislative_observation_sets","database_table","source","source_southern_legislative_observation_set","scripts/load_southern_legislative_history_warehouse.py","observation_set_id","active",None,"Provider-specific contests; overlapping source observations coexist"),
    ("southern_legislative_candidate_results","database_table","source","source_southern_legislative_candidate_result","scripts/load_southern_legislative_history_warehouse.py","source_candidate_result_id","active",None,"Candidate-party results with observed versus unknown vote status"),
    ("southern_legislative_all_observations","database_view","source","all_southern_legislative_candidate_election_observations","scripts/load_southern_legislative_history_warehouse.py","candidate_result_id + observation_set_id","active",None,"Official MEDSL and Klarner observations retained for reconciliation"),
    ("southern_legislative_canonical_table","database_table","canonical","canonical_southern_legislative_candidate_election","scripts/load_southern_legislative_history_warehouse.py","candidate_result_id","active",None,"Materialized whole-contest authority selection"),
    ("southern_legislative_history","database_view","canonical","fact_southern_legislative_candidate_election","scripts/load_southern_legislative_history_warehouse.py","candidate_result_id","active",None,"Authority-ranked Southern legislative history from all locally available years"),
    ("southern_legislative_history_coverage","database_view","qa","qa_southern_legislative_canonical_coverage","scripts/load_southern_legislative_history_warehouse.py","state_code + cycle + chamber","active",None,"Observed coverage; absent contests never become zero"),
    ("southern_legislative_final_history","database_view","mart","fact_southern_legislative_final_candidate_election","scripts/load_southern_legislative_history_warehouse.py","candidate_result_id","active","southern_legislative_history","Final regular-cycle stage; Louisiana runoff only when present"),
    ("southern_legislative_final_competition_coverage","database_view","qa","qa_southern_legislative_final_competition_coverage","scripts/load_southern_legislative_history_warehouse.py","state_code + cycle + chamber","active","southern_legislative_final_history","Observed competitions and exactly-one-D/R WAR eligibility"),
    ("southern_legislative_history_export","csv_export","canonical","data/processed/elections/southern_legislative_candidate_history.csv.gz","scripts/load_southern_legislative_history_warehouse.py","candidate_result_id","compatibility","southern_legislative_history","Deterministic compatibility export of schema-version-13 stage-level facts"),
    ("southern_legislative_final_history_export","csv_export","mart","data/processed/elections/southern_legislative_final_candidate_history.csv.gz","scripts/load_southern_legislative_history_warehouse.py","candidate_result_id","compatibility","southern_legislative_final_history","Deterministic final-stage modeling export"),
    ("southern_finance_source_files","database_table","source","source_southern_finance_file","scripts/load_southern_finance_warehouse.py","finance_source_registration_id","active",None,"Campaign-finance acquisition manifests and supplemental upstream registrations"),
    ("southern_candidate_cycle_finance_source","database_table","source","source_southern_candidate_cycle_finance","scripts/load_southern_finance_warehouse.py","finance_candidate_cycle_id","active",None,"All candidate-cycle observations including explicit unknown and review states"),
    ("southern_incumbency_evidence","database_table","source","source_southern_incumbency_evidence","scripts/load_southern_finance_warehouse.py","incumbency_evidence_id","active",None,"Workbook provider web continuity and adjudicated evidence; absence remains unknown"),
    ("southern_finance_candidate_bridge","database_table","canonical","bridge_southern_finance_candidate_identity","scripts/load_southern_finance_warehouse.py","finance_candidate_cycle_id","active",None,"Exact election-scope and conservative name evidence linking finance to final-stage candidates"),
    ("southern_candidate_finance_mart","database_view","mart","fact_southern_candidate_cycle_finance","scripts/load_southern_finance_warehouse.py","candidate_result_id","active",None,"Accepted warehouse-linked candidate-cycle finance with unknown-not-zero semantics"),
    ("southern_race_finance_mart","database_view","mart","fact_southern_race_finance","scripts/load_southern_finance_warehouse.py","state/cycle/chamber/district","active",None,"D/R fundraising ratio only when both observations and identities are complete"),
    ("southern_race_finance_model_features","csv_export","mart","data/processed/finance/southern_race_finance_model_features.csv","scripts/export_southern_finance_model_features.py","state/year/chamber/district","active",None,"Missingness-aware model interface; numeric finance features only for complete D/R races"),
    ("southern_finance_release_validation","publication","qa","data/processed/source_audits/southern_finance_release_validation.json","scripts/validate_southern_finance_release.py","validation_run","active",None,"Integrity, cardinality, identity retention, and missing-not-zero release gates"),
    ("southern_finance_remaining_gap_queue","csv_export","qa","data/processed/source_audits/southern_finance_remaining_gap_queue.csv","scripts/audit_southern_finance_remaining_gaps.py","state","active",None,"Source-specific unresolved finance gaps and repair actions; zero fill is forbidden"),
    ("southern_finance_warehouse_coverage","database_table","qa","qa_southern_finance_coverage","scripts/load_southern_finance_warehouse.py","state_code/cycle","active",None,"Separate source observation identity-link and complete-race coverage measures"),
    ("southern_war_panel_v1_source","csv_export","mart","data/processed/war/southern_war_panel_v1/southern_war_panel.csv","scripts/build_southern_war_panel_v1.py","state/year/chamber/district","active",None,"Versioned baseline and incumbency context used by the finance-free preparation layer"),
    ("southern_war_outcome","database_table","mart","mart_southern_war_outcome","scripts/load_southern_war_preparation_warehouse.py","state/cycle/chamber/district","active",None,"Exactly-one-D/R positive-vote final-stage outcomes selected without combining providers"),
    ("southern_war_context","database_table","mart","mart_southern_war_context_feature","scripts/load_southern_war_preparation_warehouse.py","state/cycle/chamber/district","active",None,"Versioned baseline and incumbency context with strict and research eligibility gates"),
    ("alabama_2026_incumbency_roster","database_table","mart","mart_alabama_2026_incumbency_roster","scripts/load_southern_war_preparation_warehouse.py","cycle/state/chamber/district","active",None,"Workbook-backed Alabama 2026 incumbency roster; corrections remain proposed until review"),
    ("southern_war_training_no_finance","database_view","mart","mart_southern_war_training_no_finance","scripts/load_southern_war_preparation_warehouse.py","state/cycle/chamber/district","active",None,"Finance-free outcome/context join with explicit readiness status"),
    ("southern_war_training_no_finance_coverage","database_view","qa","qa_southern_war_training_no_finance_coverage","scripts/load_southern_war_preparation_warehouse.py","state/cycle/chamber","active",None,"Strict research and missing-input counts for the finance-free training mart"),
    ("southern_war_training_with_finance","database_view","mart","mart_southern_war_training_with_finance","scripts/load_southern_war_preparation_warehouse.py","state/cycle/chamber/district","active",None,"Exact race-key fundraising overlay with explicit incomplete-finance status"),
    ("southern_war_training_with_finance_coverage","database_view","qa","qa_southern_war_training_with_finance_coverage","scripts/load_southern_war_preparation_warehouse.py","state/cycle/chamber","active",None,"WAR readiness and complete-finance coverage reported separately"),
    ("southern_war_training_no_finance_export","csv_export","mart","data/processed/war/finance_free_southern_war/southern_war_training_no_finance.csv","scripts/load_southern_war_preparation_warehouse.py","state/cycle/chamber/district","compatibility","southern_war_training_no_finance","Versioned export with finance explicitly excluded"),
    ("southern_war_training_with_finance_export","csv_export","mart","data/processed/war/finance_free_southern_war/southern_war_training_with_finance.csv","scripts/load_southern_war_preparation_warehouse.py","state/cycle/chamber/district","active","southern_war_training_with_finance","Versioned incumbency and finance evaluation interface"),
    ("alabama_2026_incumbency_review_export","csv_export","qa","data/processed/war/finance_free_southern_war/alabama_2026_incumbency_review.csv","scripts/load_southern_war_preparation_warehouse.py","cycle/state/chamber/district","compatibility","alabama_2026_incumbency_roster","Review queue for workbook disagreements with the prior forecast roster"),
    ("raw_southern_presidential_context","raw_file","raw","data/raw/presidential/southern_war_v4/","scripts/acquire_southern_war_v4_context.py","source artifact + SHA-256","active",None,"Immutable presidential context files; national companion assets may remain under historical_statewide_elections"),
    ("southern_context_source_files","database_table","source","source_southern_context_file","scripts/load_southern_context_warehouse.py","source_file_id","active",None,"Acquired context artifacts with registration and normalization status kept distinct"),
    ("southern_presidential_geography_results","database_table","source","source_southern_presidential_geography_result","scripts/load_southern_context_warehouse.py","source/state/cycle/geography_type/geography_id","active",None,"Presidential totals at provider precinct or explicitly derived Census-block grain"),
    ("southern_presidential_geography_facts","database_view","canonical","fact_southern_presidential_geography_result","scripts/load_southern_context_warehouse.py","result_observation_id","active",None,"Validated presidential geography rows; review reconciliations excluded"),
    ("southern_geography_layers","database_table","canonical","dim_southern_geography_layer","scripts/load_southern_context_warehouse.py","geography_layer_id","active",None,"Versioned state-cycle-chamber legislative boundary layers"),
    ("southern_geography_units","database_table","canonical","dim_southern_geography_unit","scripts/load_southern_context_warehouse.py","geography_layer_id/source_geoid","active",None,"Normalized WGS84 district geometry with feature hashes"),
    ("southern_result_geography_bridge","database_table","canonical","bridge_southern_result_geography","scripts/load_southern_context_warehouse.py","result_observation_id/geography_unit_id","active",None,"Explicit matches and allocation weights only; empty is a valid not-yet-joined state"),
    ("southern_context_ingest_qa","database_table","qa","qa_southern_context_ingest","scripts/load_southern_context_warehouse.py","source_file_id","active",None,"Source-row, vote, and geometry reconciliation status"),
    ("southern_context_assignment_manifest","csv_export","source","data/processed/source_audits/southern_context_assignment_manifest.csv","scripts/acquire_southern_context_assignments.py","source_file_id","active",None,"Immutable national block-assignment archive lineage with plan vintage and SHA-256"),
    ("southern_assignment_source_files","database_table","source","source_southern_assignment_file","scripts/build_southern_context_allocations.py","source_file_id","active",None,"Warehouse registrations for parsed national state-legislative block-assignment archives"),
    ("southern_block_district_assignments","database_table","canonical","bridge_southern_block_district_assignment","scripts/build_southern_context_allocations.py","source/state/block_geoid","active",None,"Exact 2020 Census block membership in lower- and upper-chamber election plans"),
    ("southern_presidential_district_result_mart","database_table","mart","mart_southern_presidential_district_result","scripts/build_southern_context_allocations.py","result source/assignment source/state/election/plan/chamber/district","active",None,"Presidential district totals aggregated through one explicit block-assignment source"),
    ("southern_presidential_district_result_fact","database_view","mart","fact_southern_presidential_district_result","scripts/build_southern_context_allocations.py","district_result_id","active","southern_presidential_district_result_mart","Only state-chamber allocations that pass vote conservation"),
    ("southern_presidential_district_allocation_qa","database_table","qa","qa_southern_presidential_district_allocation","scripts/build_southern_context_allocations.py","result source/assignment source/state/chamber","active",None,"Source-versus-allocated vote conservation and block coverage"),
    ("southern_presidential_district_result_export","csv_export","mart","data/processed/presidential/southern_context_allocations/presidential_district_results.csv","scripts/build_southern_context_allocations.py","district_result_id","active","southern_presidential_district_result_fact","Versioned compatibility export of validated district results"),
    ("southern_presidential_district_allocation_export","csv_export","qa","data/processed/presidential/southern_context_allocations/allocation_reconciliation.csv","scripts/build_southern_context_allocations.py","state/plan/chamber","active","southern_presidential_district_allocation_qa","Versioned allocation reconciliation export"),
    ("raw_southern_2016_vest_context","raw_file","raw","data/raw/presidential/southern_war_v4/vest_2016/","scripts/acquire_southern_2016_precinct_geography.py","state archive + SHA-256","active",None,"Immutable CC BY 4.0 VEST 2016 precinct result and geometry archives"),
    ("southern_2016_vest_manifest","csv_export","source","data/processed/source_audits/southern_2016_vest_manifest.csv","scripts/acquire_southern_2016_precinct_geography.py","source_file_id","active",None,"Pinned Dataverse version file IDs hashes terms retrieval times and geography vintages"),
    ("southern_vest_context_source_files","database_table","source","source_southern_vest_context_file","scripts/load_southern_2016_vest_warehouse.py","source_file_id","active",None,"One normalized VEST 2016 result-and-geometry archive per Southern state"),
    ("southern_vest_context_ingest_qa","database_table","qa","qa_southern_vest_context_ingest","scripts/load_southern_2016_vest_warehouse.py","source_file_id","active",None,"Per-state feature result geometry repair and one-to-one link audit"),
    ("raw_southern_2020_census_blocks","raw_file","raw","data/raw/census/tl_2020_*_tabblock20.zip","scripts/acquire_southern_2020_census_blocks.py","state archive + SHA-256","active",None,"Immutable official TIGER2020 Census tabulation-block polygons for the 14-state crosswalk"),
    ("southern_2020_census_block_manifest","csv_export","source","data/processed/source_audits/southern_2020_census_block_manifest.csv","scripts/acquire_southern_2020_census_blocks.py","source_file_id","active",None,"Official Census block URL retrieval hash terms vintage and authoritative-scope lineage"),
    ("southern_census_block_source_files","database_table","source","source_southern_census_block_file","scripts/build_southern_2016_vest_plan_allocation.py","source_file_id","active",None,"Warehouse registration of the 14 TIGER2020 block geometry archives used by the crosswalk"),
    ("southern_vest_precinct_district_weights","database_table","canonical","bridge_southern_vest_precinct_district_weight","scripts/build_southern_2016_vest_plan_allocation.py","result/assignment/chamber/district","active",None,"VEST precinct shares on the 2022 plan weighted by 2020 block VAP with labeled area fallback"),
    ("southern_vest_plan_allocation_qa","database_table","qa","qa_southern_vest_precinct_plan_allocation","scripts/build_southern_2016_vest_plan_allocation.py","result source/assignment source/chamber","active",None,"Coverage split fallback unmatched-VAP and precinct-weight validation"),
    ("southern_vest_plan_district_result_export","csv_export","mart","data/processed/presidential/southern_vest_2016_allocations/presidential_district_results.csv","scripts/build_southern_2016_vest_plan_allocation.py","district_result_id","active","southern_presidential_district_result_fact","Validated VEST 2016 presidential results on the enacted 2022 plan"),
    ("southern_vest_plan_allocation_export","csv_export","qa","data/processed/presidential/southern_vest_2016_allocations/crosswalk_validation.csv","scripts/build_southern_2016_vest_plan_allocation.py","state/chamber","active","southern_vest_plan_allocation_qa","Versioned precinct crosswalk validation export"),
]

LINEAGE = [
    ("southern_war_training_with_finance","southern_historical_war_release","features"),
    ("southern_war_v3_release","southern_historical_war_release","reconciles"),
    ("southern_historical_war_release","southern_war_map_payload","exports"),
    ("southern_map_geometry_manifest","southern_war_map_payload","exports"),
    ("southern_war_map_payload","southern_war_map_join_audit","validates"),
    ("source_vote_observations","vote_quality_review","validates"),
    ("raw_sos_elections","source_repair_audit","validates"),
    ("raw_legiscan","source_repair_audit","validates"),
    ("legiscan_rollcalls_table","legiscan_reconciliation","validates"),
    ("legiscan_votes_table","legiscan_reconciliation","validates"),
    ("legiscan_reconciliation","legiscan_complete_rollcalls","reconciles"),
    ("legiscan_complete_rollcalls","legiscan_complete_votes","reconciles"),
    ("legiscan_votes_table","legiscan_complete_votes","reconciles"),
    ("raw_sos_elections","source_vote_observations","normalizes"),
    ("source_vote_observations","canonical_votes","reconciles"),
    ("source_vote_observations","canonical_candidates","reconciles"),
    ("canonical_candidates","people","reconciles"),
    ("canonical_candidates","candidate_elections","reconciles"),
    ("canonical_candidates","candidate_aliases","reconciles"),
    ("canonical_candidates","cmo_feature_mart","features"),
    ("cmo_feature_mart","published_cmo_v4_data","exports"),
    ("raw_legiscan","legiscan_bills_csv","normalizes"),
    ("raw_legiscan","legiscan_votes_csv","normalizes"),
    ("legiscan_bills_csv","legiscan_bills_table","normalizes"),
    ("legiscan_votes_csv","legiscan_votes_table","normalizes"),
    ("legiscan_bills_table","legiscan_rollcalls_table","reconciles"),
    ("legiscan_rollcalls_table","legiscan_votes_table","reconciles"),
    ("legiscan_bills_table","legiscan_sponsors_table","reconciles"),
    ("candidate_elections","canonical_legislator_identity","reconciles"),
    ("raw_finance","candidate_finance_mart","features"),
    ("raw_finance","dime_recipients","normalizes"),
    ("dime_recipients","candidate_resource_mart","features"),
    ("candidate_resource_mart","race_resource_mart","features"),
    ("race_resource_mart","dime_finance_build_manifest","validates"),
    ("raw_census","precinct_district_weights","reconciles"),
    ("raw_southern_sos_elections","southern_election_source_files","normalizes"),
    ("southern_election_source_files","southern_candidate_results","normalizes"),
    ("southern_election_source_files","southern_election_coverage","validates"),
    ("southern_candidate_results","southern_candidate_facts","reconciles"),
    ("southern_candidate_facts","southern_candidate_results_export","exports"),
    ("raw_southern_legislative_history","southern_legislative_observation_sets","normalizes"),
    ("southern_legislative_observation_sets","southern_legislative_candidate_results","normalizes"),
    ("southern_candidate_facts","southern_legislative_all_observations","reconciles"),
    ("southern_legislative_candidate_results","southern_legislative_all_observations","reconciles"),
    ("southern_legislative_all_observations","southern_legislative_canonical_table","reconciles"),
    ("southern_legislative_canonical_table","southern_legislative_history","exports"),
    ("southern_legislative_history","southern_legislative_history_coverage","validates"),
    ("southern_legislative_history","southern_legislative_final_history","features"),
    ("southern_legislative_final_history","southern_legislative_final_competition_coverage","validates"),
    ("southern_legislative_history","southern_legislative_history_export","exports"),
    ("southern_legislative_final_history","southern_legislative_final_history_export","exports"),
    ("southern_finance_source_files","southern_candidate_cycle_finance_source","normalizes"),
    ("southern_candidate_cycle_finance_source","southern_finance_candidate_bridge","reconciles"),
    ("southern_incumbency_evidence","alabama_2026_incumbency_roster","features"),
    ("southern_finance_candidate_bridge","southern_candidate_finance_mart","features"),
    ("southern_candidate_finance_mart","southern_race_finance_mart","features"),
    ("southern_race_finance_mart","southern_finance_warehouse_coverage","validates"),
    ("southern_race_finance_mart","southern_race_finance_model_features","exports"),
    ("southern_race_finance_model_features","southern_finance_release_validation","validates"),
    ("southern_finance_warehouse_coverage","southern_finance_remaining_gap_queue","validates"),
    ("southern_legislative_all_observations","southern_war_outcome","features"),
    ("southern_legislative_final_history","southern_war_outcome","features"),
    ("southern_war_panel_v1_source","southern_war_context","features"),
    ("southern_war_outcome","southern_war_training_no_finance","features"),
    ("southern_war_context","southern_war_training_no_finance","features"),
    ("southern_war_training_no_finance","southern_war_training_no_finance_coverage","validates"),
    ("southern_war_training_no_finance","southern_war_training_no_finance_export","exports"),
    ("alabama_2026_incumbency_roster","alabama_2026_incumbency_review_export","exports"),
    ("raw_southern_presidential_context","southern_context_source_files","normalizes"),
    ("southern_context_source_files","southern_presidential_geography_results","normalizes"),
    ("southern_context_source_files","southern_geography_layers","normalizes"),
    ("southern_geography_layers","southern_geography_units","normalizes"),
    ("southern_presidential_geography_results","southern_presidential_geography_facts","reconciles"),
    ("southern_presidential_geography_results","southern_result_geography_bridge","reconciles"),
    ("southern_geography_units","southern_result_geography_bridge","reconciles"),
    ("southern_context_source_files","southern_context_ingest_qa","validates"),
    ("southern_context_assignment_manifest","southern_assignment_source_files","normalizes"),
    ("southern_assignment_source_files","southern_block_district_assignments","normalizes"),
    ("southern_presidential_geography_facts","southern_presidential_district_result_mart","features"),
    ("southern_block_district_assignments","southern_presidential_district_result_mart","features"),
    ("southern_presidential_district_result_mart","southern_presidential_district_allocation_qa","validates"),
    ("southern_presidential_district_result_mart","southern_presidential_district_result_fact","reconciles"),
    ("southern_presidential_district_result_fact","southern_presidential_district_result_export","exports"),
    ("southern_presidential_district_allocation_qa","southern_presidential_district_allocation_export","exports"),
    ("raw_southern_2016_vest_context","southern_2016_vest_manifest","validates"),
    ("southern_2016_vest_manifest","southern_vest_context_source_files","normalizes"),
    ("southern_vest_context_source_files","southern_presidential_geography_results","normalizes"),
    ("southern_vest_context_source_files","southern_geography_layers","normalizes"),
    ("southern_vest_context_source_files","southern_vest_context_ingest_qa","validates"),
    ("raw_southern_2020_census_blocks","southern_2020_census_block_manifest","validates"),
    ("southern_2020_census_block_manifest","southern_census_block_source_files","normalizes"),
    ("southern_census_block_source_files","southern_vest_precinct_district_weights","features"),
    ("southern_result_geography_bridge","southern_vest_precinct_district_weights","features"),
    ("southern_block_district_assignments","southern_vest_precinct_district_weights","features"),
    ("southern_vest_precinct_district_weights","southern_vest_plan_allocation_qa","validates"),
    ("southern_vest_precinct_district_weights","southern_presidential_district_result_mart","features"),
    ("southern_presidential_district_result_fact","southern_vest_plan_district_result_export","exports"),
    ("southern_vest_plan_allocation_qa","southern_vest_plan_allocation_export","exports"),
]


def main() -> None:
    columns=["asset_id","asset_kind","layer","locator","owner_script","key_description",
             "status","replacement_asset_id","notes"]
    output=ROOT/"project_docs"/"data_catalog.csv"
    with output.open("w", encoding="utf-8", newline="") as stream:
        writer=csv.writer(stream)
        writer.writerow(columns)
        writer.writerows(ASSETS)
    with closing(connect()) as connection:
        initialize(connection)
        connection.executemany("""INSERT INTO warehouse_asset
          (asset_id,asset_kind,layer,locator,owner_script,key_description,status,replacement_asset_id,notes)
          VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(asset_id) DO UPDATE SET
          asset_kind=excluded.asset_kind,layer=excluded.layer,locator=excluded.locator,
          owner_script=excluded.owner_script,key_description=excluded.key_description,
          status=excluded.status,replacement_asset_id=excluded.replacement_asset_id,notes=excluded.notes""",ASSETS)
        connection.executemany("INSERT OR REPLACE INTO warehouse_asset_lineage VALUES (?,?,?)",LINEAGE)
        connection.commit()
    print(f"Cataloged {len(ASSETS)} assets and {len(LINEAGE)} lineage edges: {output}")


if __name__=="__main__":main()
