"""Build an interactive gallery of branded editorial design directions."""

from __future__ import annotations

import base64
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PORTRAIT = Path(r"C:\Users\User\Desktop\images.jfif")
OUTPUT = ROOT / "artifacts" / "site" / "design-directions.html"


def build() -> str:
    portrait = base64.b64encode(PORTRAIT.read_bytes()).decode("ascii")
    return r'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Jackson Hannan · Site design directions</title>
<style>
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--ink);background:var(--paper);font-family:var(--sans);line-height:1.45}button,select{font:inherit}button{cursor:pointer}a{color:inherit}.lab{position:sticky;top:0;z-index:50;display:flex;align-items:center;gap:16px;padding:10px 18px;background:#15110f;color:#fff;border-bottom:1px solid #ffffff2b}.lab strong{font:600 11px var(--mono);letter-spacing:.08em;text-transform:uppercase;white-space:nowrap}.lab-group{display:flex;gap:5px;flex-wrap:wrap}.lab button{border:1px solid #ffffff38;background:transparent;color:#ddd;padding:6px 9px;font:500 10px var(--mono)}.lab button.active{background:#f2e8d7;color:#211b18;border-color:#f2e8d7}.lab-note{margin-left:auto;color:#aaa;font:400 10px var(--mono)}
:root{--paper:#dbeaf2;--panel:#eef5f8;--ink:#211b1b;--muted:#5e6870;--rule:#9db4c1;--accent:#743b42;--accent2:#a86742;--blue:#355875;--blue-party:#3f7198;--red-party:#a34b44;--serif:Georgia,'Times New Roman',serif;--sans:Arial,Helvetica,sans-serif;--cond:'Arial Narrow',Arial,sans-serif;--mono:Consolas,'Courier New',monospace;--max:1240px}
.site-head{border-bottom:1px solid var(--rule);background:var(--paper)}.head-inner{max-width:var(--max);margin:auto;min-height:94px;padding:15px 26px;display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:20px}.identity{display:flex;align-items:center;gap:13px;text-decoration:none}.portrait{width:56px;height:56px;object-fit:cover;object-position:center 35%;filter:saturate(.78) contrast(1.03)}.wordmark b{display:block;font:600 25px/1 var(--serif);letter-spacing:-.4px}.wordmark span{display:block;margin-top:5px;font:500 9px var(--mono);letter-spacing:.12em;text-transform:uppercase;color:var(--accent)}.main-nav{display:flex;justify-content:center;gap:23px}.main-nav a{text-decoration:none;font:600 11px var(--sans)}.social{font:500 11px var(--mono);text-decoration:none}.social:before{content:'@';color:var(--accent)}
.page{max-width:var(--max);margin:auto;padding:40px 26px 90px}.page-intro{display:grid;grid-template-columns:minmax(0,820px) 1fr;gap:48px;align-items:end;padding-bottom:22px;border-bottom:2px solid var(--ink)}.label{font:600 10px var(--mono);letter-spacing:.08em;text-transform:uppercase;color:var(--accent)}h1{margin:9px 0 11px;font:700 clamp(36px,4.5vw,58px)/1.03 var(--sans);letter-spacing:-1.7px}.dek{max-width:760px;margin:0;font:400 17px/1.5 var(--sans);color:var(--muted)}.dateline{text-align:right;font:500 10px/1.7 var(--mono);color:var(--muted)}.dateline b{color:var(--ink)}
.lede-grid{display:grid;grid-template-columns:1.35fr .65fr;gap:34px;margin-top:26px}.primary-figure{min-height:470px;border:1px solid var(--rule);background:var(--panel);position:relative;overflow:hidden}.figure-head{display:flex;justify-content:space-between;padding:15px 17px;border-bottom:1px solid var(--rule)}.figure-head b{font:600 15px var(--sans)}.figure-head span{font:500 9px var(--mono);color:var(--muted)}.map-art{position:absolute;inset:55px 0 0;background:linear-gradient(28deg,transparent 48%,#b9aa9c55 49%,transparent 51%),linear-gradient(132deg,transparent 46%,#b9aa9c45 47%,transparent 49%);clip-path:polygon(19% 4%,72% 0,91% 18%,88% 70%,64% 96%,28% 92%,7% 62%)}.map-art:after{content:'';position:absolute;inset:5% 12%;background:repeating-linear-gradient(83deg,#0000 0 31px,var(--rule) 32px 33px),repeating-linear-gradient(6deg,#0000 0 40px,var(--rule) 41px 42px);opacity:.55}.map-focus{position:absolute;left:42%;top:38%;width:19%;height:23%;background:var(--accent);opacity:.8;clip-path:polygon(12% 0,100% 18%,79% 100%,0 72%)}.legend{position:absolute;left:16px;bottom:15px;display:flex;gap:3px}.legend i{width:31px;height:7px;background:var(--red-party)}.legend i:nth-child(2){opacity:.65}.legend i:nth-child(3){background:#d8cec1}.legend i:nth-child(4){background:var(--blue-party);opacity:.65}.legend i:nth-child(5){background:var(--blue-party)}
.view-controls{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-top:24px;padding:10px 0;border-top:1px solid var(--rule);border-bottom:1px solid var(--rule)}.tab-set{display:flex;gap:0}.tab-set button{padding:8px 14px;border:1px solid var(--ink);background:transparent;color:var(--ink);font:700 11px var(--sans)}.tab-set button+button{border-left:0}.tab-set button.active{background:var(--ink);color:var(--paper)}.cycle-control{display:flex;align-items:center;gap:9px;font:600 10px var(--mono);text-transform:uppercase}.cycle-control select{min-width:120px;padding:7px 28px 7px 9px;border:1px solid var(--ink);background:var(--panel);color:var(--ink)}
.rail{border-top:4px solid var(--accent)}.rail-block{padding:17px 0;border-bottom:1px solid var(--rule)}.rail-block small{font:500 9px var(--mono);color:var(--muted);text-transform:uppercase}.rail-block strong{display:block;margin-top:4px;font:600 28px var(--serif)}.rail-block p{margin:6px 0 0;font:400 13px/1.5 var(--sans);color:var(--muted)}.seatline{height:9px;margin-top:11px;display:flex;background:#ddd}.seatline i:first-child{width:31%;background:var(--blue-party)}.seatline i:last-child{width:69%;background:var(--red-party)}
.section-title{display:flex;align-items:end;justify-content:space-between;margin:64px 0 16px;padding-bottom:9px;border-bottom:1px solid var(--ink)}.section-title h2{margin:0;font:600 31px var(--serif);letter-spacing:-.5px}.section-title span{font:500 9px var(--mono);color:var(--muted)}.race-table{width:100%;border-collapse:collapse}.race-table th{text-align:left;padding:9px 8px;border-bottom:2px solid var(--ink);font:600 9px var(--mono);text-transform:uppercase;color:var(--muted)}.race-table td{padding:13px 8px;border-bottom:1px solid var(--rule);font-size:12px}.race-table td:nth-child(2){font:600 15px var(--serif)}.rating{display:inline-block;padding:2px 7px;border:1px solid currentColor;font:600 9px var(--mono)}
.metric-ledger{display:grid;grid-template-columns:repeat(4,1fr);border-top:2px solid var(--ink);border-bottom:1px solid var(--rule);margin-top:28px}.metric{padding:15px 18px 18px 0}.metric+.metric{padding-left:18px;border-left:1px solid var(--rule)}.metric b{display:block;font:600 31px var(--serif)}.metric span{font:500 9px/1.4 var(--mono);color:var(--muted);text-transform:uppercase}.scatter-art{height:390px;margin:25px 0 0 52px;border-left:1px solid var(--ink);border-bottom:1px solid var(--ink);position:relative}.scatter-art:before{content:'';position:absolute;inset:0;background:linear-gradient(to right,transparent 49.8%,var(--rule) 50%,transparent 50.2%),linear-gradient(to top,transparent 49.8%,var(--rule) 50%,transparent 50.2%)}.scatter-art i{position:absolute;width:10px;height:10px;border-radius:50%;background:var(--blue-party);border:1px solid var(--paper)}.scatter-art i.r{background:var(--red-party)}.scatter-note{max-width:630px;margin:13px 0 0 52px;font:400 12px/1.55 var(--sans);color:var(--muted)}
.candidate-grid{display:grid;grid-template-columns:300px 1fr;gap:46px;margin-top:30px}.candidate-card{border-top:4px solid var(--accent);padding-top:15px}.candidate-card .portrait{width:116px;height:116px}.candidate-card h2{margin:13px 0 4px;font:600 32px var(--serif)}.candidate-card p{margin:0;color:var(--muted);font-size:13px}.candidate-facts{display:grid;grid-template-columns:1fr 1fr;border-top:2px solid var(--ink)}.candidate-facts div{padding:15px 10px 16px 0;border-bottom:1px solid var(--rule)}.candidate-facts b{display:block;font:600 23px var(--serif)}.candidate-facts span{font:500 9px var(--mono);color:var(--muted);text-transform:uppercase}.timeline{margin-top:28px}.timeline article{display:grid;grid-template-columns:95px 1fr;gap:20px;padding:15px 0;border-top:1px solid var(--rule)}.timeline time{font:500 10px var(--mono);color:var(--accent)}.timeline h3{margin:0 0 5px;font:600 18px var(--serif)}.timeline p{margin:0;font-size:13px;color:var(--muted)}
.method-layout{display:grid;grid-template-columns:210px minmax(0,740px);gap:55px;margin-top:34px}.contents{position:sticky;top:74px;align-self:start;border-top:3px solid var(--ink);padding-top:10px}.contents a{display:block;padding:5px 0;text-decoration:none;font:500 10px var(--mono);color:var(--muted)}.article section{padding:0 0 34px;margin-bottom:34px;border-bottom:1px solid var(--rule)}.article h2{font:600 29px var(--serif)}.article p,.article li{font:400 17px/1.7 var(--serif)}.equation{padding:17px 0;border-top:1px solid var(--ink);border-bottom:1px solid var(--ink);font:500 19px var(--serif);text-align:center}
.footer{border-top:1px solid var(--rule);padding:25px 26px 38px;max-width:var(--max);margin:auto;display:flex;justify-content:space-between;font:500 10px var(--mono);color:var(--muted)}
body.ledger{--paper:#e7f0f4;--panel:#f8fbfc;--ink:#202426;--muted:#59666c;--rule:#afc1c9;--accent:#a25f3d;--accent2:#743b42;--blue:#3d6077;--max:1320px}body.ledger .head-inner{min-height:76px}body.ledger .portrait{width:43px;height:43px;border-radius:50%}body.ledger .wordmark b{font:700 21px var(--sans)}body.ledger h1{font-family:var(--sans);font-weight:700;font-size:clamp(38px,5vw,63px);line-height:1;max-width:870px}body.ledger .page-intro{border-top:6px solid var(--accent);padding-top:25px}body.ledger .primary-figure{background:var(--panel)}body.ledger .rail{border-top-color:var(--ink)}body.ledger .section-title h2,body.ledger .rail-block strong,body.ledger .metric b,body.ledger .candidate-card h2,body.ledger .candidate-facts b,body.ledger .timeline h3,body.ledger .article h2{font-family:var(--sans)}
body.night{--paper:#182332;--panel:#202e3e;--ink:#f0e6d7;--muted:#b6a99c;--rule:#465566;--accent:#c36c49;--accent2:#8b4545;--blue:#7e9fba;--blue-party:#759fbd;--red-party:#c16e61;--max:1260px}body.night .site-head{background:#111a25}body.night .portrait{width:62px;height:62px;border-radius:50%;border:2px solid var(--accent)}body.night .wordmark b{font-family:var(--cond);font-size:31px;text-transform:uppercase;letter-spacing:.5px}body.night .wordmark span{color:var(--accent)}body.night .page-intro{grid-template-columns:1fr 270px}body.night h1{font-family:var(--cond);font-weight:700;text-transform:uppercase;letter-spacing:-1px;line-height:.9}body.night .dek{color:#d0c4b7}body.night .primary-figure{box-shadow:inset 0 0 50px #0003}body.night .rating{background:var(--accent);color:#111;border:0}body.night .scatter-art i{border-color:var(--paper)}
.direction-note{position:fixed;right:14px;bottom:14px;z-index:20;max-width:280px;padding:11px 13px;background:var(--ink);color:var(--paper);border:1px solid var(--rule);font:500 10px/1.5 var(--mono)}
@media(max-width:850px){.lab{align-items:flex-start;overflow:auto}.lab-note{display:none}.head-inner{grid-template-columns:1fr auto}.main-nav{display:none}.page{padding:32px 18px 65px}.page-intro,.lede-grid,.candidate-grid,.method-layout,body.night .page-intro{grid-template-columns:1fr}.dateline{text-align:left}.metric-ledger{grid-template-columns:1fr 1fr}.method-layout{gap:25px}.contents{position:static}.social{display:none}}@media(max-width:520px){.wordmark b{font-size:20px}.portrait{width:45px;height:45px}h1{font-size:42px}.metric-ledger{grid-template-columns:1fr}.metric+.metric{padding-left:0;border-left:0;border-top:1px solid var(--rule)}.primary-figure{min-height:380px}.direction-note{display:none}}
</style></head><body class="field">
<div class="lab"><strong>Palette directions</strong><div class="lab-group" id="themes"><button data-theme="field" class="active">A · Blue / oxblood</button><button data-theme="ledger">B · Blue / copper</button><button data-theme="night">C · Deep slate</button></div><div class="lab-group" id="pages"><button data-page="forecast" class="active">Forecast</button><button data-page="cmo">CMO</button><button data-page="ideology">Ideology</button><button data-page="candidate">Candidate atlas</button><button data-page="method">Methodology</button></div><span class="lab-note">Working design study · not the live site</span></div>
<header class="site-head"><div class="head-inner"><a class="identity" href="#"><img class="portrait" src="data:image/jpeg;base64,__PORTRAIT__" alt="Jackson Hannan"><span class="wordmark"><b>Jackson Hannan</b><span>Alabama elections & political geography</span></span></a><nav class="main-nav"><a href="#">Forecast</a><a href="#">Overperformance</a><a href="#">Ideology</a><a href="#">Candidates</a><a href="#">Methods</a></nav><a class="social" href="https://x.com/electionsjack">electionsjack</a></div></header>
<main id="view"></main><footer class="footer"><span>Jackson Hannan · Alabama election models</span><span>GitHub · Substack · LinkedIn · @electionsjack</span></footer><div class="direction-note" id="directionNote"></div>
<script>
const portrait='data:image/jpeg;base64,__PORTRAIT__';
const dots=Array.from({length:82},(_,i)=>`<i class="${i%4===0?'r':''}" style="left:${7+(i*37)%89}%;bottom:${7+(i*61)%86}%"></i>`).join('');
const shell=(label,title,dek,content,meta='Updated August 21, 2026')=>`<div class="page"><header class="page-intro"><div><div class="label">${label}</div><h1>${title}</h1><p class="dek">${dek}</p></div><div class="dateline"><b>${meta}</b><br>Models and analysis by Jackson Hannan<br>@electionsjack</div></header>${content}</div>`;
const pages={
forecast:()=>shell('Alabama legislative elections · 2026','Alabama Legislative Forecast','District-level win probabilities and expected margins for Alabama State House and State Senate elections.',`<div class="lede-grid"><div class="primary-figure"><div class="figure-head"><b>State Senate · Democratic win probability</b><span>SELECT A DISTRICT</span></div><div class="map-art"><i class="map-focus"></i></div><div class="legend"><i></i><i></i><i></i><i></i><i></i></div></div><aside class="rail"><div class="rail-block"><small>Expected chamber composition</small><strong>26 R · 9 D</strong><div class="seatline"><i></i><i></i></div></div><div class="rail-block"><small>Most competitive district</small><strong>SD–2</strong><p>Democratic win probability: 58%. Open seat.</p></div><div class="rail-block"><small>Selected model</small><strong>Fundamentals+</strong><p>Recent-cycle CMO expectation with finance and district variables.</p></div></aside></div><div class="section-title"><h2>Competitive districts</h2><span>ROUNDED PROBABILITIES</span></div><table class="race-table"><thead><tr><th>District</th><th>Contest</th><th>Forecast</th><th>Expected margin</th><th>Rating</th></tr></thead><tbody><tr><td>SD–2</td><td>Open seat · Madison County</td><td>58% D</td><td>D+1.4</td><td><span class="rating">Toss-up</span></td></tr><tr><td>HD–21</td><td>Rex Reynolds vs. challenger</td><td>91% R</td><td>R+9.8</td><td><span class="rating">Likely R</span></td></tr><tr><td>HD–32</td><td>Barbara Boyd vs. Republican</td><td>64% D</td><td>D+3.2</td><td><span class="rating">Lean D</span></td></tr></tbody></table>`),
cmo:()=>shell('Historical candidate analysis · 1994–2024','Candidate Margin Overperformance','Legislative candidate margins compared with district-level expected margins.',`<div class="view-controls"><div class="tab-set" aria-label="Chamber"><button class="active">State House</button><button>State Senate</button></div><label class="cycle-control">Election cycle <select><option>2024</option><option>2022</option><option>2018</option><option>2014</option><option>2010</option><option>2006</option><option>2002</option><option>1998</option><option>1994</option></select></label></div><div class="metric-ledger"><div class="metric"><b>1994–2024</b><span>Cycles covered</span></div><div class="metric"><b>1,084</b><span>Candidate-cycles</span></div><div class="metric"><b>+18.8</b><span>Largest durable federal advantage</span></div><div class="metric"><b>80 / 20</b><span>District / statewide baseline</span></div></div><div class="lede-grid"><div class="primary-figure"><div class="figure-head"><b>State House · 2024 CMO</b><span>SELECT A DISTRICT</span></div><div class="map-art"><i class="map-focus"></i></div><div class="legend"><i></i><i></i><i></i><i></i><i></i></div></div><aside class="rail"><div class="rail-block"><small>Selected candidate</small><strong>Barbara Boyd</strong><p>Democratic · House District 32 · 2022</p></div><div class="rail-block"><small>Actual margin</small><strong>D+1.6</strong><p>Expected baseline: R+11.2 · CMO: +12.8</p></div><div class="rail-block"><small>Federal baseline</small><strong>R+13.4</strong><p>Same-cycle federal margin in the district.</p></div></aside></div><div class="section-title"><h2>Candidate-cycle results</h2><span>HOVER FOR RACE DATA</span></div><div class="scatter-art">${dots}</div><p class="scatter-note">Each point represents one candidate-cycle. The vertical axis shows performance relative to the expected legislative margin. The horizontal axis shows district partisanship.</p>`),
ideology:()=>shell('Candidate ideology analysis','Ideology and Electoral Performance','Associations between absolute candidate ideology, candidate margin overperformance, and performance relative to federal baselines.',`<div class="metric-ledger"><div class="metric"><b>+12.9</b><span>Democratic CMO per ideology SD rightward</span></div><div class="metric"><b>+18.8</b><span>Federal advantage per SD</span></div><div class="metric"><b>−9.0</b><span>Republican slope moving rightward</span></div><div class="metric"><b>407</b><span>Candidate-cycles with Shor scores</span></div></div><div class="section-title"><h2>Absolute ideology and federal-baseline performance</h2><span>SHADED AREA: COMMON SUPPORT</span></div><div class="scatter-art">${dots}</div><p class="scatter-note">Coefficients describe historical associations. Positive candidate-directed values indicate performance above the applicable federal baseline. Estimates are reported separately by party.</p>`),
candidate:()=>shell('Candidate records','Candidate Profile','Election results, district context, finance, incumbency, legislative votes, and public-position evidence for an individual candidate.',`<div class="candidate-grid"><aside class="candidate-card"><img class="portrait" src="${portrait}" alt=""><h2>Example candidate</h2><p>Democratic legislator · House District 32</p><div class="rail-block"><small>General-election record</small><strong>4–1</strong><p>Five appearances since 2014.</p></div></aside><div><div class="candidate-facts"><div><b>+9.4</b><span>Career average CMO</span></div><div><b>+14.1</b><span>Federal baseline advantage</span></div><div><b>$184k</b><span>Cycle fundraising</span></div><div><b>0.31</b><span>Absolute ideology score</span></div></div><div class="timeline"><article><time>2022</time><div><h3>General-election result</h3><p>Won House District 32 by 1.6 points. Federal-baseline advantage: 14.7 points.</p></div></article><article><time>2018–22</time><div><h3>Issue-position summary</h3><p>Gun access, Christian sexual morality, economic policy, and rural public-service positions derived from reviewed evidence.</p></div></article><article><time>EVIDENCE</time><div><h3>23 reviewed observations</h3><p>Sources include roll calls, Vote Smart responses, campaign statements, and sponsorship records.</p></div></article></div></div></div>`),
method:()=>shell('Model documentation','Forecast Methodology','Definitions, data sources, model components, probability calibration, validation results, and limitations.',`<div class="method-layout"><nav class="contents"><div class="label">Contents</div><a href="#">1 · Target quantity</a><a href="#">2 · Data sources</a><a href="#">3 · Baseline</a><a href="#">4 · Candidate variables</a><a href="#">5 · Probability</a><a href="#">6 · Validation</a><a href="#">7 · Limitations</a></nav><article class="article"><section><div class="label">01 · Target quantity</div><h2>Forecast output</h2><p>The forecast output is the expected Democratic two-party margin in each legislative district. The model starts from recent district-level electoral behavior, adjusts for the projected environment, and incorporates candidate-specific evidence.</p></section><section><div class="label">02 · Model views</div><h2>Basic and Fundamentals+</h2><p>The Basic model uses the 80/20 baseline specification. Fundamentals+ uses the full recent-cycle candidate-margin expectation and the additional validated variables documented below.</p><div class="equation">Expected margin = district baseline + environment + candidate adjustment</div></section><section><div class="label">03 · Limitations</div><h2>Data limitations</h2><p>Alabama has few comparable modern cycles, finance reporting is uneven, and unopposed races do not provide observed two-party margins. Probability calibration uses recent Southern legislative results.</p></section></article></div>`)
};
const notes={field:'A · Blue / oxblood — portrait-derived powder blue with dark oxblood rules and headings. Strongest connection to the photograph.',ledger:'B · Blue / copper — a quieter gray-blue field with copper emphasis and charcoal text. More neutral and utilitarian.',night:'C · Deep slate — dark slate with copper and muted blue. Highest contrast; best reserved for election-night use.'};
const params=new URLSearchParams(location.search),validPages=Object.keys(pages),validThemes=Object.keys(notes);let page=validPages.includes(params.get('page'))?params.get('page'):'forecast',theme=validThemes.includes(params.get('theme'))?params.get('theme'):'field';document.body.className=theme;
function setUrl(){const url=new URL(location);url.searchParams.set('theme',theme);url.searchParams.set('page',page);history.replaceState({},'',url)}function syncButtons(){document.querySelectorAll('[data-theme]').forEach(x=>x.classList.toggle('active',x.dataset.theme===theme));document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page))}function render(){document.querySelector('#view').innerHTML=pages[page]();document.querySelector('#directionNote').textContent=notes[theme];syncButtons();setUrl()}
document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{theme=b.dataset.theme;document.body.className=theme;render()});document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});render();
</script></body></html>'''.replace("__PORTRAIT__", portrait)


def main() -> None:
    if not PORTRAIT.exists():
        raise FileNotFoundError(f"Brand portrait not found: {PORTRAIT}")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(build(), encoding="utf-8")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
